### ISSUE TITLE
Daikin 3HHT ETBH16DA9W

### ISSUE THREAD

**Issue by luetzow** [raomin/ESPAltherma#101]
Hello, I have some issues while readinng the Current and Voltage from the device. Any ideas for a configuration file or registers for my device?

Most important is to get the right current. The device is connected with 3 phases and 400V.

How do I calculate electrical power consumption?

P = 400V x Current x SQRT(3)?

I read following values:

{0x21,0,105,2,-1,"INV Primary Current [A]"},
{0x21,2,105,2,-1,"INV Secondary Current [A]"},
{0x21,4,101,2,-1,"Voltage (N-phase) [V]"},
{0x21,2,101,2,-1,"Voltage (N-phase) (V)2"},

"INV Primary Current [A]": 3.1,
"INV Secondary Current [A]": 6.5,
 "Voltage (N-phase) [V]": 188,
 "Voltage (N-phase) (V)2": 65

**Comment by raomin** [comment]
Please have a look at the discussion here: https://github.com/raomin/ESPAltherma/discussions/184
It will tell you what are these values and how you can use them.
