### ISSUE TITLE
compatibilité  altherma 3 ETVH16S18EA6V et jeedom

### ISSUE THREAD

**Issue by azsono03** [raomin/ESPAltherma#104]
Bonjour a tous

J'aimerais savoir quel modèle sélectionner pour ma PAC altherma 3 ETVH16S18EA6V?

Comment intégrer les résultats a jeedom par un plugin spécifique à espaltherma qui récupère les infos directement avec un widget spécifique ?

Est-il possible d'accédé directement au m5stick par son adresse ip un peu comme sur espeasy ?

Merci d'avance de vos réponses

**Comment by raomin** [comment]
Bonjour @azsono03 

There is no risk into testing different config file. Yours seems to be a 16k, I would try with `ALTHERMA(LT_CA_CB_11-16KW).h`
I have no idea about jeedom. I guess it can read mqtt data, so I believe it would work.

ESPAltherma has no web interface. It is in the roadmap though...

_Essaie de poster des quesions en anglais tu auras plus de chance d'avoir des réponses..._
