### ISSUE TITLE
OTA update m5stick plus

### ISSUE THREAD

**Issue by jangarga** [raomin/ESPAltherma#112]
try to configure m5stick to update firmware by OTA, but during firmware upload system show below error:
![error](https://user-images.githubusercontent.com/73886990/170878954-18024dd4-587c-496f-b356-dec37c67cd55.png)

can you help me?

**Comment by munzili** [comment]
try to replace the  upload_port in platformio.ini with the IP of the ESP32

**Comment by jangarga** [comment]
already try, but have still problem

**Comment by jangarga** [comment]
![error2](https://user-images.githubusercontent.com/73886990/170879717-64a743f3-9fed-41f1-895f-2db4fc87b7b3.png)

**Comment by munzili** [comment]
Are you sure its the correct ip? Can you ping it?

**Comment by raomin** [comment]
Also, as the ESP is connecting subsequently to the pc, one common issue is that the connection will be blocked by the firewall on the PC. Make sure it's deactivated for the time of the update.

**Comment by jangarga** [comment]
> Also, as the ESP is connecting subsequently to the pc, one common issue is that the connection will be blocked by the firewall on the PC. Make sure it's deactivated for the time of the update.

With your instruction, working fine, thanks for support
