### ISSUE TITLE
State of the sensor.althermasensors is allways in unknown (none) state

### ISSUE THREAD

**Issue by andreytse** [raomin/ESPAltherma#113]
Is it possible to change or override forever state of the sensor.althermasensors?
It is allways in unknown (none) state

upd.
Maybe it will be good to know about esp32 or m5 is still reading something from Altherma. I mean if any attribute was readed from heating pump so sensor state = On, if no one register was readed, sensor state = off

**Comment by Gollam** [comment]
I adjusted it manually to Online in the code, but I agree, this would be more meaningful.

**Comment by munzili** [comment]
I will take a look into this after i finished the WebUI feature pullrequest.

**Comment by raomin** [comment]
Finally found some time to fix it!
![image](https://user-images.githubusercontent.com/4460208/202875259-1b02060d-393f-4f44-b287-31c7d812818c.png)
It's now set to the main state. Online/Offline.
