### ISSUE TITLE
OutdoorAirTemp_R1T

### ISSUE THREAD

**Issue by mgx0** [raomin/ESPAltherma#114]
Hello,

ONECTA App requested a firmware update for my heat pump so I have installed it.

now I am getting incorrect readings here: 
{0x20,0,105,2,1,"OutdoorAirTemp_R1T"} <- shows 11.5 instead of 20 degrees Celsius. On the HeatPump screen there is 20 degrees outside displayed. You can see the point where the temperatures have started reporting weirdly, in the attached screenshot, look at date 05/05, this is the firmware update date.

how can I make a "debug" version of ESPAltherma to see which register now contains the OutdoorAirTemp_R1T temperature please?

I am not asking anyone to fix it for me, I want to find it myself but I need to show a good way to do it

thanks
![Screenshot 2022-06-06 at 21 05 43](https://user-images.githubusercontent.com/9897026/172229709-9883c5a4-1fde-4a5e-a129-22222068059f.png)

**Comment by raomin** [comment]
That's super weird... You did not change anything on your ESPAltherma? 
What happens if you disconnect the thermostat?

**Comment by mgx0** [comment]
Nope nothing has changed, “only” firmware update

Thermostat was connected 2 weeks after this behaviour has started, so it does not have much to do with this. 

Other values seem to be reported okay. 

I have noticed one thing: when there is no heating at all, the Outdoor temp is not reported properly. But if there is DHW heating in progress, outdoor temp starts to be reported okay. I’ll attach an example screenshot

**Comment by mgx0** [comment]
I'm sorry I was wrong. It is not the firmware update that broke this. Looking at attached screenshot, the date when the outdoor temperature started to be reported incorrectly seems to be the date I turned off the floor heating completely




![Screenshot 2022-06-06 at 22 09 20](https://user-images.githubusercontent.com/9897026/172239909-e7d64542-3d0f-4efb-bc30-acb153e8870f.png)
I

**Comment by mgx0** [comment]
Yes I have slept it over and it makes sense. Fair point, thanks
