### ISSUE TITLE
COP calculation using a ShellyEM

### ISSUE THREAD

**Issue by alexdelli** [raomin/ESPAltherma#120]
Hi everybody, anyone can help me with COP calculation using a shelly em?
I try this but COP is Zero every time for now. Is it possible to mix espaltherma sensors and Shelly sensors?

`      espaltherma_cop:
        friendly_name: "COP"
        value_template: "{% if is_state_attr('sensor.althermasensors','Operation Mode', 'Heating') and is_state_attr('sensor.althermasensors','Freeze Protection', 'OFF') %}
{{
((state_attr('sensor.althermasensors','Flow sensor (l/min)')| float * 0.06 * 1.16 * (state_attr('sensor.althermasensors','Leaving water temp. before BUH (R1T)') | float - state_attr('sensor.althermasensors','Inlet water temp.(R4T)')|float) )
/
(state_attr('sensor.shellyem_5e1757_channel_2_power') | float ))
|round(2)
}}
{% else %} 0 {%endif%}"
        unit_of_measurement: 'COP'`

thank you

**Comment by BigFoot2020** [comment]
Use `states('sensor.shellyem_5e1757_channel_2_power')` instead of state_attr, the you should get actual power value from Shelly EM.

**Comment by alexdelli** [comment]
> Use `states('sensor.shellyem_5e1757_channel_2_power')` instead of state_attr, the you should get actual power value from Shelly EM.

Thank you, I’ll try

**Comment by alexdelli** [comment]
it works :)
