### ISSUE TITLE
Broken JSON in case heat pump returns NULL value

### ISSUE THREAD

**Issue by DieterTHeck** [raomin/ESPAltherma#121]
Hi,

due to whatever reason, my heatpumps returns "nothing" when querying 
{0x60,5,203,1,-1,"Betrieb_Störung_x60"}

This is taken over 1:1 in the MQTT JSON file, which causes "broken JSON format" errors downstream
![grafik](https://user-images.githubusercontent.com/58054042/178671288-dd37d8b5-a701-4716-99d4-9ea5558e9f11.png)

I assume the code needs to be changed to put a null into the JSON in such cases

Thanks for investigating!

**Comment by raomin** [comment]
Hi @DieterTHeck. I've seen where it is. Thanks for reporting. I'll fix it ASAP.

**Comment by raomin** [comment]
Ok, it should be fixed now!

**Comment by DieterTHeck** [comment]
Hi,
thanks, brilliant. 
I just 
1) updated converter.h with lastest version
2) recompiled without error
3) OTA update works fine with the buggy NULL value re-enabled
4) MQTT shows "-" now
![grafik](https://user-images.githubusercontent.com/58054042/179547371-0349ebf1-7cbd-4bda-bd3e-b8a30e7ff3e3.png)
5) Home Assistant templates work w/o errors now

Looks like it is working :-)
