### ISSUE TITLE
Compatibility with ekhbx016ab

### ISSUE THREAD

**Issue by dgaussin** [raomin/ESPAltherma#125]
Hi

I've found an very old Daikin altherma ekhbx016ab in my new home. I check the install manual but no X10A mention I think. How to be sure if ESPAltherma is compatible or not ?

Thanks

**Comment by raomin** [comment]
Hello @dgaussin
Look closely on the board. But if you cannot find the x10a port, then it's probably too old.

**Comment by raomin** [comment]
@dgaussin did you find your port?
You can have a look at #145, it's also a very old one but has a x10a port.

**Comment by raomin** [comment]
Hello @dgaussin, can you give some update? Can we close this issue?
