### ISSUE TITLE
M5StickCPlus and 2 relays for SG1 and SG2

### ISSUE THREAD

**Issue by dandjo** [raomin/ESPAltherma#130]
# SmartGrid Features

Is it possible to control two relais to switch SG1 and SG2 with a M5StickCPlus? And if yes, could someone provide a circuit diagram? Thank you very much.

**Comment by dandjo** [comment]
Can I use pin 32 and 33 of the M5StickC Plus? Which Relays do you recommend?

![image](https://user-images.githubusercontent.com/34278179/186278651-ae29e4ce-a034-4143-8ff4-59425a55881a.png)

**Comment by DieterTHeck** [comment]
Should work, check fotos here...
https://github.com/raomin/ESPAltherma/issues/17#issuecomment-1078870240

In the firmware there are 3 pins to be individually defined for SG1/SG2 and thermostat. 
Maybe try if they switch before you put it on your heat pump

**Comment by raomin** [comment]
@dandjo can I close this one?

**Comment by dandjo** [comment]
Yes, please close.
