### ISSUE TITLE
M5StickC Display

### ISSUE THREAD

**Issue by ste-ka** [raomin/ESPAltherma#132]
Hello,

I have flashed the Stick in your discription with the ESPAltherma SW.

Unfortunately the display shows some strange things..
![WhatsApp Image 2022-08-31 at 09 29 52](https://user-images.githubusercontent.com/112542191/187619573-cb2a1855-63bd-4d35-93b1-0d65e6d1e2cd.jpeg)

can anyone help my please?

**Comment by ste-ka** [comment]
solved!

**Comment by raomin** [comment]
Yep, you probably had a M5 C Plus...
