### ISSUE TITLE
ESPAltherma

### ISSUE THREAD

**Issue by Alexander-Wehner** [raomin/ESPAltherma#133]
Hallo, ich wollte mal fragen ob ich das ESPAlthermaaucg bei meiner Daikin altherma verwenden kann?

Gruß Alex

![20220830_213304](https://user-images.githubusercontent.com/112548044/187647997-206e36af-4a87-494b-9e1c-d32ef62c1aa1.jpg)
![20220831_112027](https://user-images.githubusercontent.com/112548044/187648007-c5675dd9-a960-4232-b2bf-74560d452483.jpg)
![20220831_112139](https://user-images.githubusercontent.com/112548044/187648015-b886229c-0e81-43b2-a74f-c1df619f1917.jpg)
![20220831_112220](https://user-images.githubusercontent.com/112548044/187648020-28c0c103-e744-4aa4-a138-acbb04f4309c.jpg)
![20220831_112225](https://user-images.githubusercontent.com/112548044/187648023-1e3ed438-1f85-447c-ae47-fcc4378f0f92.jpg)
![20220831_112307](https://user-images.githubusercontent.com/112548044/187648027-8533a9b4-0096-4c5d-ba64-a5a032aa4230.jpg)
![20220831_112318](https://user-images.githubusercontent.com/112548044/187648031-88e83df9-0d7b-475f-b819-bcd62ad6ca78.jpg)

**Comment by raomin** [comment]
Hi @Alexander-Wehner 

I don't know for sure as it's a 13 year old model ; but it seems that there is a X10A port on your board, so it's definitely worth trying...
![image](https://user-images.githubusercontent.com/4460208/187648919-bb1607d5-bbf8-4443-99c7-22a4b86d90aa.png)


(please keep messages here in English)

**Comment by Alexander-Wehner** [comment]
Hi,ok, what do i need?--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 31.08.22, 11:41 schrieb Raomin ***@***.***>:

   
  Hi @Alexander-Wehner 
  I don't know for sure as it's a 13 year old model ; but it seems that there is a X10A port on your board, so it's definitely worth trying...  
  (please keep messages here in English)

**Comment by raomin** [comment]
err.... you need to read the Readme document and follow the instructions...
https://github.com/raomin/ESPAltherma

**Comment by Alexander-Wehner** [comment]
Hello, I have an old Daikin Altherma heat pump, to this I have connected the M5StackC plus via the 8-pin X10A connector, I unfortunately do not get any data on my home assistant, what can be the reason? Greeting Alex


![20220917_171728](https://user-images.githubusercontent.com/112548044/190864527-fe8ebeb0-afe5-49e1-9f0b-35f8cac3eb18.jpg)


![20220917_171719](https://user-images.githubusercontent.com/112548044/190864541-4fec8324-bf82-4469-a8ca-caf79c03d7b8.jpg)


![20220917_073120](https://user-images.githubusercontent.com/112548044/190864553-d73b11c7-2b3f-4ac7-a460-30a99d153054.jpg)


![20220917_073025](https://user-images.githubusercontent.com/112548044/190864567-afbc0308-f703-4dc8-a168-a11b0c9f9f38.jpg)


![20220917_171708](https://user-images.githubusercontent.com/112548044/190864574-b415ed58-4e02-4ed3-8ac9-6fc70dd0af28.jpg)
