### ISSUE TITLE
Error ets Jan  8 2013,rst cause:2, boot mode:(3,6) at NodeMCUV2

### ISSUE THREAD

**Issue by Goofman2** [raomin/ESPAltherma#135]
Yesterday compiled program in platformIO for a NodeMCUV2 (ESP8266) and it worked. Now I cannot compile a working firmware.bin. Nothing chanegd as far as I can see. Don't know where to start....

**Comment by raomin** [comment]
The error on the title is not a compilation error but a boot message from the ESP.
Give more details / screenshot of your issue.
(You can simply copy paste images here)

**Comment by Goofman2** [comment]
I know, it's the serial debug port and as far as I cab see it's the WD.

![image](https://user-images.githubusercontent.com/113108680/189130992-92d68a59-1680-4c1f-9f0b-a2b283dfee0c.png)

**Comment by Goofman2** [comment]
Can someone share complete .pio folder, maybe it's a version of the header files which are not correct.

**Comment by raomin** [comment]
On ESP8266, some users reported issues with the use of PROGMEM.
Just remove it from the `default.h` definition file you're using and try again.

**Comment by raomin** [comment]
Hello @Goofman2, what your situation now?

**Comment by skrgahr** [comment]
i had same issue on NodeMCU v3. board did not start. with removing PROGMEM it finally started.

**Comment by raomin** [comment]
I guess it's solved.
