### ISSUE TITLE
NodeMCUV2 pinning serial port

### ISSUE THREAD

**Issue by Goofman2** [raomin/ESPAltherma#136]
It's not clear for me which pins should be used for serial communication with the Altherma. Code says PIN 16 (RX) and PIN 17 (TX). These pinnumbers are not mentioned on the nodemcu schematics

**Comment by raomin** [comment]
Hello @Goofman2,

On ESP8266, the GPIO internal numbers are usually masked behind sequential D1, D2, D3 aliases that are mapped by the compiler settings to internal GPIO (eg 16, 17).
You can usualy find the corresponding GPIO on the pinout schema. Eg, on a NodeMCU:
![image](https://user-images.githubusercontent.com/4460208/189121762-77b627f8-484f-40f4-a2a5-9b3bb80bcab8.png)
Here, GPIO16 correspond to D0, and GPIO17 is not exposed.

So, if you want to use D7 and D8 as RX, TX you would set in the `setup.h` line 26-27:
```c
#define RX_PIN    13// Pin connected to the TX pin of X10A 
#define TX_PIN    15// Pin connected to the RX pin of X10A
```
