### ISSUE TITLE
two espaltherma same homeassistant

### ISSUE THREAD

**Issue by ralf2025** [raomin/ESPAltherma#150]
Could you tell me how I can have two espaltherma in the same home assistant? I want to control two Daikin Althermas in the same HomeAssistant installation. Can I? What should I change in the code so that the mqtt messages are not confused?
Thanks

**Comment by raomin** [comment]
Hi @ralf2025, welcome and thanks for your support.
Have a look at this same question opened 2 weeks ago #140
You'll find the things you need to change.

**Comment by ralf2025** [comment]
Thanks for the speed and I apologize for not having found it earlier. :-)
