### ISSUE TITLE
M5 Stick C Plus dead after 

### ISSUE THREAD

**Issue by haz-69** [raomin/ESPAltherma#173]
First time evere using PlatformIO sp i think i do something wrong.
Opened the folder ESPAltherma-main. and then entered my settings for WIFI and MQTT in src/setup,h. Nothing else where changed.
After pressing F1  : PlatformIO: Upload them M5 Stick C plus is totaly dead?
What have i been missing?

**Comment by haz-69** [comment]
After F1 PlatformOP:Upload PlatforIO says: enviroment esp32 SUCCESS  but it is still dead?

**Comment by irecord** [comment]
Does the M5 Stick power up if you plug the USB cable in to power it? Can you confirm if you are getting 5v from the connector?

**Comment by haz-69** [comment]
Yes when it is programmed with Easyloadr_M5STickC_Plus_FactoryTest, but not after above
![Skärmbild 2022-10-20 173834](https://user-images.githubusercontent.com/74374387/196994960-494af867-45ac-4e04-bcc7-f4b4279ec8e5.jpg)

**Comment by irecord** [comment]
What did you do to solve it?

**Comment by haz-69** [comment]
Changed settings in platformIO rx and tx pin eas not defined and wrong environment
