### ISSUE TITLE
Loss of connectivity - was WiFi connection fall down

### ISSUE THREAD

**Issue by coralblack12** [raomin/ESPAltherma#191]
I'm using a module NodeMCU 8266, I'm able to see Altherma data for days but suddenly the card loose connection and the red light start blinking very fast. Even if I try to reset the card or disconnect the power, nothing gonna change. I've replaced the card with a new one, but after one week, the problem is the same.
Only if I reprogram the card with same configuration it starts connecting again but just for few days. What could be the problem?
Thanks

**Comment by raomin** [comment]
Do you see logs on Serial/USB when the card is blinking red?

**Comment by raomin** [comment]
I too witness connection loss, might have been introduced by a recent code change.
It looks like this in the graphs, and the AlthermaSensor entity becomes _Unavailable_
![image](https://user-images.githubusercontent.com/4460208/203762086-2f782761-fdb3-4673-bef4-0ba8bc7610d4.png)

I'll keep an eye on it.

**Comment by coralblack12** [comment]
At the moment I have assigned a fixed IP to the Altherma in order to exclude DHCP problem. Since now no issue, but let's wait a couple of weeks

**Comment by raomin** [comment]
I've set an alert on my phone in case of loss of connection. 
On my side it happened during heating phase.

**Comment by coralblack12** [comment]
Even if I've set the static IP address it seems the problem is still occuring. Now my suspect is about the power supply. My ESP is using the power of Altherma pin X10A.
I've tried to disconnect that connection and connecting a USB power supply but, doing this, the card is stopping to providing data to home assistant anymore.

**Comment by raomin** [comment]
Looks like there are issues with the wifi selection when multiple AP broadcast the same SSID. In this case, the ESP might randomly choose the weaker one. See #224 and #213 
Is it your case?

**Comment by coralblack12** [comment]
Dear Raomin, 
It seems I have solved in this way:
- replacing the ESP32 with a different model. Now I'm using the narrow one, with pin RX2/TX2 instead of GPIO 16 and 17.
- connecting the power via USB cable and still connecting the ground to the Altherma pin.

In the last month I did not noticed any WiFi interruption.
Thanks
