### ISSUE TITLE
[Question] Altherma 3 RF+W with WT32-ETH01

### ISSUE THREAD

**Issue by pstarkl** [raomin/ESPAltherma#204]
Hi everyone!

I´m trying to use esp-altherma with my heat-pump (EHBX08EF9W) with a WT32-ETH01
I have successfully swapped the WiFi-Connection with an Ethernet-Connection and deploying the project was also successfuly.

However when I connect the WT32 to my heat-pump, my payload only looks like this:
![image](https://user-images.githubusercontent.com/99012238/206400596-90fc0b1f-dbc1-455c-a9a6-62441fef01c9.png)

But I enabled a lot more values than one, as seen here:
![image](https://user-images.githubusercontent.com/99012238/206400855-6e08c584-3cd6-4e2d-8f9c-cf5af388e45a.png)

I also hooked up the WT32 to the heat-pump and used the serial monitor, which gave me this output:
<img width="558" alt="Bildschirm­foto 2022-12-08 um 09 49 27" src="https://user-images.githubusercontent.com/99012238/206401276-76179567-0497-49f7-a49b-9c4321dca2b0.png">

So I assume, the reading from 0x00 was successful after 3 attempts, but those multiple timeouts are not normal I guess.
What do I have to change in my settings in order to bring this project to work properly? (Baud-rate etc?)

Thanks a lot

**Comment by raomin** [comment]
Check your connection. A complete time out means that ESPAltherma didn't get anything from the heat pump.
Pay close attention to your GND connection, it should be properly linking ESP GND to the Heat pump GND.
Sometimes, dupont wires are broken with no sign outside.

**Comment by pstarkl** [comment]
Hi, thanks for your reply, I really appreciate it.
I already triple checked the connections, im using PIN4 for RX and PIN5 for TX on the WT32, according to this pinout:
https://files.seeedstudio.com/products/102991455/WT32-ETH01_datasheet_V1.1-%20en.pdf

![image](https://user-images.githubusercontent.com/99012238/206842569-9e69c0be-5935-4737-bcd5-63acf3d2748e.png)

I also see the built in LED on the WT32 blinking when it is connected to the heat-pump:

![image](https://user-images.githubusercontent.com/99012238/206842628-35b8399f-6f3e-4259-8929-c8f5205692c4.png)

However I constantly get this output:

![image](https://user-images.githubusercontent.com/99012238/206842647-811d1834-e8b0-4226-9650-b25e168d1b8c.png)

Also tried using SoftwareSerial instead of HardwareSerial, which made no difference at all /:

Do you have any ideas on how to get this to run?
Thank you

**Comment by pstarkl** [comment]
hello again!

I am finally getting data out of my daikin using the WT32 🥳 
the problem was the length of the dupont wires! 🙄 
I had connected 2 dunpont wires in a row for the pins to increase the length, but apperantly that causes the timeout!

**Comment by bwindsor** [comment]
@pstarkl Would you mind sharing how you swapped the WiFi connection with an Ethernet one please?

**Comment by pstarkl** [comment]
@bwindsor Yeah sure, I will publish the code in a few days :)

**Comment by Alibloke** [comment]
@pstarkl did you publish the code?

**Comment by ivanleovitanza** [comment]
> @Alibloke did you find the code?
