### ISSUE TITLE
Is ESPAltherma compatible with EKHHE260CV37?

### ISSUE THREAD

**Issue by djfanatix** [raomin/ESPAltherma#230]
Hi,

I am looking into buying the EKHHE260CV37 (Daikin Heat pump for Hot water)
According to the manual there is a connection for Wifi.
Is this compatible?
<img width="571" alt="Scherm­afbeelding 2023-01-09 om 10 58 29" src="https://user-images.githubusercontent.com/43752712/211282859-4bc0b75b-d921-4c87-a037-926823fdba80.png">

**Comment by Tardymo** [comment]
Might not be. Board and user interface is completely different and there is no 5 pin serial connector.

**Comment by raomin** [comment]
Indeed, not much luck on this. It's not an altherma model. Sorry
