### ISSUE TITLE
Home Assistant - Integration sg is not supported

### ISSUE THREAD

**Issue by dg1yds** [raomin/ESPAltherma#234]
Hello,

I am just "playing" with ESPAltherma, my M5 Stick and PlatformIO.
I am still waiting for the delivery of the heat pump, but I'll play something with the tool in advance.
The configuration and flashing worked without any problems - thank you in advance for the tool and your work.

I would like to use the smart grid function and have configured it accordingly.
I am using Home Assistant 2023.1.6 and the integration of ESPAltherma via mqtt is generally working, although the ESP is not connected to the heat pump. I can see internal values via sensor.althermasensors.

But I think the smart grid integration is somehow "wrong" with my HA version; I can see the following warning in the log; additionally I have added a screenshot of the MQTT data.
A sensor for the smart grid functionally is not available in HA.

**HA log**
"WARNING (MainThread) [homeassistant.components.mqtt.discovery] Integration sg is not supported"

![image](https://user-images.githubusercontent.com/17652957/213883465-136ef89c-6ec7-43a5-b68b-87946bb8798b.png)

I am not sure if this is a bug or an issue with my configuration or environment; perhaps you can check.

**Comment by colseven** [comment]
Same here. I use SG Switch with this Code in configuration.yaml

`mqtt:      
  switch:
    - name: "SG Altherma"
      state_topic: "espaltherma/sg/state"
      command_topic: "espaltherma/sg/set"
      payload_on: "2"
      payload_off: "0"`

![bild 2023-02-06 um 05 06 42](https://user-images.githubusercontent.com/63189272/216881593-76502225-8a29-4fd5-a556-9608bb95dfb7.jpg)

**Comment by dg1yds** [comment]
Hi,
I am not a programmer but I have modified the original code to provide a selector within HA.
I have also carried over some ideas from another open PR (https://github.com/raomin/ESPAltherma/pull/110)

You can try https://github.com/dg1yds/ESPAltherma.
I have merged hopefully all my stuff to the repo.

Give it a try; I can setup an official PR afterwards.
