### ISSUE TITLE
ESPAltherma not working on ESP8266

### ISSUE THREAD

**Issue by b0b33140** [raomin/ESPAltherma#239]
Hello,
I have an esp8266 NodeMcu V2 CP2102, I followed the procedure to install ESPAltherma but the firmware does not seem to start. I have a blue led next to D0 which flashes every 2 seconds and the serial monitor writes every 2 seconds:

load 0x4010f000, len 3424, room 16
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8
tail 0
chksum 0x2b
csum 0x2b
v00054bc0
~ld

My ESP8266 does not even connect to my wifi network, I tried to install Tasmota and the Wifi and MQTT works perfectly.

**Comment by raomin** [comment]
Try removing PROGMEM.

**Comment by b0b33140** [comment]
Thanks ! I deleted PROGMEM in the ALTHERMA(BIZONE_CB_04-08KW).h file and everything started working.

**Comment by Drealine** [comment]
Same issue here. 
Maybe a fixe for this ?

**Comment by raomin** [comment]
I removed PROGMEM from the source code. Not used in esp32, and breaking in esp8266.

**Comment by Drealine** [comment]
> I removed PROGMEM from the source code. Not used in esp32, and breaking in esp8266.

Ok thanks a lot!
