### ISSUE TITLE
Dead m5stick

### ISSUE THREAD

**Issue by MJankeN** [raomin/ESPAltherma#248]
Hi
I have 2 dead m5stick. Both brand new. The first one started reading low battery, after the CODE. Turned OFF and never came back to life again.
The second one, CODE uploaded. Turned it OFF on the BUTTON. Dead it is.
Any help would be nice. 
Got two m5stick, a brand new Altherma, a Raspberry Pi with mqtt setup. All ready to go. But this program seem to take the best of me and the hardware.
Thanks

**Comment by raomin** [comment]
Unlikely dead. Describe a bit more what you did and what you see when you plug them in or upload code. 
Plug the in USB to your pc. If you hear a Windows sound, they're not dead. 
It takes 7 long seconds to start from the button.

**Comment by MJankeN** [comment]
Windows sound when plugged in, yes. Pushed the ON button formore then 15 sec. Nothing.

**Comment by raomin** [comment]
What happens when you upload the code?

**Comment by MJankeN** [comment]
Failed to connect. Error Code 2.

**Comment by MJankeN** [comment]
Managed to upload the code, and then the problem started.

**Comment by MJankeN** [comment]
Uploaded again. Success it says, but it is pitch dark in the screen and not connecting to wifi. LED used to flash, but not now.

**Comment by raomin** [comment]
You're using M5StickC, or M5StickC+?
Make sure to select the right profile on the blue bar as said in the Readme [here](https://github.com/raomin/ESPAltherma#step-1-uploading-the-firmware) Step 2.

**Comment by MJankeN** [comment]
Good point with the right profile. Checking later today.

**Comment by raomin** [comment]
Good! Glad to hear. Have fun!

**Comment by MJankeN** [comment]
But. There is always a but. It came through on the MQTT. There is something missing in the entities. It only shows that it is online?

![Daikin online](https://user-images.githubusercontent.com/122159820/219099359-6aba738c-18e0-4e8f-9407-0eaa3e216cad.JPG)
