### ISSUE TITLE
problem installing on esp8266

### ISSUE THREAD

**Issue by J1Buskens** [raomin/ESPAltherma#256]
I am trying to install this on esp8266.
The esp was not connecting to router, so I disconnected from the Heatpump and connected to the serial monitor over usb.
I am getting the following:

```
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3424, room 16
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8
tail 0
chksum 0x2b
csum 0x2b
v00053a10
~ld
```

**Comment by J1Buskens** [comment]
fixed by removing PROGMEM from code

**Comment by raomin** [comment]
BTW I removed PROGMEM from the source code. Not used in esp32, and breaking in esp8266.
