### ISSUE TITLE
Newer models with no X10 port

### ISSUE THREAD

**Issue by J1Buskens** [raomin/ESPAltherma#259]
I have an Altherma EHVX08S23EJ9W, which doesn’t seem to have an X10 port.
I tried the X9 port but it doesn’t seem t have the same protocol.
Is there any way to use ESPAltherma on this system?
(Attached a picture of the control [board)]
![C87B4F11-B816-4674-ABE6-5954E3C61328](https://user-images.githubusercontent.com/35972725/223072457-5ae5dc73-d137-4d4d-af4d-716533688266.jpeg)

**Comment by stomko11** [comment]
It doesn't seem like you are looking at the right board? Did you check board under the metal cover?

**Comment by KalaNagHTD** [comment]
It‘s definitely the wrong board! The board A1P is needed!Am 06.03.2023 um 10:42 schrieb stomko11 ***@***.***>:﻿
It doesn't seem like you are looking at the right board? Did you check board under the metal cover?

**Comment by J1Buskens** [comment]
This is the board on the indoor unit. The board on the outdoor unit had all ports named S...
Attached a picture of the board in the outdoor unit:
![image](https://user-images.githubusercontent.com/35972725/223384871-0294865f-2cdd-4cf3-97cc-1f64a827b335.jpeg)

**Comment by stomko11** [comment]
Wrong board. There should be additional board under metal plate on indoor unit.

**Comment by J1Buskens** [comment]
> Wrong board. There should be additional board under metal plate on indoor unit.

Thanks, was able to find the board
