### ISSUE TITLE
Relay switch on Jeedom

### ISSUE THREAD

**Issue by inakifeliu** [raomin/ESPAltherma#29]
First of all thanks for such great project!

I'm running HA and Jeedom, and while in HA the switch is created, in jeedom no, and I can't find the way to...

Any help would be apreciated!!

Iñaki

**Comment by eldi0s** [comment]
I have no experience with Jeedom. Is the sensor working in Jeedmo? 

If you haven't tried you may take a look at issue https://github.com/raomin/ESPAltherma/issues/12
Maybe Jeedmo needs the same JSON table as ioBroker

**Comment by inakifeliu** [comment]
Hi @eldi0s,

The sensor is working properly. I attach the screenshot.

![Captura (55)](https://user-images.githubusercontent.com/2342439/108846127-81743c00-75de-11eb-830b-863efb2322a4.png)

Thanks for your time!

**Comment by eldi0s** [comment]
I can see some users reporting issues that MQTT plugin for Jeedom doesn't automatically detect their switches, but adding them manually woks like a charm. Have you tried this?

**Comment by eldi0s** [comment]
Another user mentioned when he first issued a manual command to the switch, it got picked up by the auto detection of Jeedom.
Just a guess syntax unknown and untested

In your Jeedom MQTT plugin, go to commands. Add a command action. Give it a name
As topic enter 
`espaltherma/POWER`
As value enter 
`{"POWER":"ON"}`

**Comment by inakifeliu** [comment]
Thank you @eldi0s, it worked!

I attach the configuration of the MQTT plugin in case it can help to anyone else...

![Captura (56)](https://user-images.githubusercontent.com/2342439/109006925-dd58c680-76ab-11eb-9d03-1e59f112f92e.png)
