### ISSUE TITLE
Hot water not working

### ISSUE THREAD

**Issue by MathieuLH44** [raomin/ESPAltherma#309]
Hello,

After connected the ESP32 and a relay, I can control the heating, but I the heating pump doesn't heat the DHW.

Someone can explain me how have the heating and the temperature of the DHW in the same time ?

Thank you

**Comment by bugac** [comment]
> Someone can explain me how have the heating and the temperature of the DHW in the same time ?

ask the person who installed heat pump for you

**Comment by MathieuLH44** [comment]
I bought the house the last year, so I don't know the company which installed it.

I think I found the problem, I turn off the DHW, but the heating was always on.
