### ISSUE TITLE
Missing ATTR Value in ioBroker MQTT

### ISSUE THREAD

**Issue by aendue** [raomin/ESPAltherma#33]
Hi, I have a Altherma 3 R ECH20 (EHSX08P50DA) and used the def/German/ALTHERMA(HPSU6_ULTRA).h include on my M5StickC.
On ioBroker I dont get the ATTR Value with the json. 
See: [https://ibb.co/0Vn5gZ3](url)

Somebody an idea? Is this the right include?

BR

**Comment by eldi0s** [comment]
Did you try this? ioBroker expects a different json format.

https://github.com/raomin/ESPAltherma/issues/12

**Comment by KalaNagHTD** [comment]
Anyway you should see that:

![CA55ECDC-C4F3-4E5C-A426-3A25961BE8B1](https://user-images.githubusercontent.com/77481230/111606079-25649800-87d7-11eb-8312-4dec6301ea72.jpeg)

**Comment by raomin** [comment]
Hello @aendue, did you manage to get this working with the clarifications from @KalaNagHTD?
Can we close this issue?

**Comment by aendue** [comment]
Hi, thanks so far. I'm going to try it this week again. Will let you know end of the week. BR

**Comment by raomin** [comment]
I believe you found what you were looking for, I'm closing it, feel free to reopen if needed.
