### ISSUE TITLE
Support Altherma 3 R W

### ISSUE THREAD

**Issue by membersound** [raomin/ESPAltherma#337]
Hello,

I have the Daikin Altherma 3 R W Model, EHBX and ERGA.
Maybe you can support it? Or which existing configuration comes close to it?
It's a simple split-device only for underfloor heating.

**Comment by raomin** [comment]
I updated the file names. It should be better for finding the right definition now:
Altherma(ERGA E EHV-EHB-EHVZ E_EJ series 04-08kW).h
