### ISSUE TITLE
I don' see history for my attributes

### ISSUE THREAD

**Issue by gattigianluca** [raomin/ESPAltherma#340]
Hi all,
I had to re-install homeassistant but, my bad, I have not done backup of configuration.yaml.
I have configured it again but now i am not able to see anymore the history of the attributes I have entered in the configuration.yaml.
What I am doing wrong? I'm getting mad 👎 
Attached the configuration.yaml and the history I see in HA
Thanks for the ones willing to help me!

![Cattura](https://github.com/raomin/ESPAltherma/assets/121362016/ee4f1e69-9cc0-4d68-ad03-c827674a159c)
[configuration.yaml.txt](https://github.com/raomin/ESPAltherma/files/13197845/configuration.yaml.txt)

**Comment by jeroenvdheuvel** [comment]
Did you enable the [Home assistant recorder](https://www.home-assistant.io/integrations/recorder/)? You can configure the number of days to keep via the argument: `purge_keep_days`.

**Comment by gattigianluca** [comment]
Yes it is enable by the default_config:  that is at the beginnin of the configuration.yaml

**Comment by gattigianluca** [comment]
Solved, I was calling wrongly the entity :-
