### ISSUE TITLE
Altherma 2

### ISSUE THREAD

**Issue by gybais** [raomin/ESPAltherma#349]
Hi raomin,

First of all, thanks for you amazing work. 

I managed to get it working on M5, and all values comes to HA.

Only one question remains for me : I used the DEFAULT.h file, as I was not sure which one I should have used.

Can you tell me which file is the best for an Altherma 2 (EHVH04S18CB) ? Thanks !

**Comment by rolisr** [comment]
Hi Gybais,

Try this ALTHERMA(LT_CA_CB_04-08KW). I have Alterma 2 too and that file works well.
