### ISSUE TITLE
Altherma 3 R F 

### ISSUE THREAD

**Issue by TLongstride** [raomin/ESPAltherma#355]
Hi,

I have a daikin Altherma 3 R F EHVH04S18EA6V and don't know witch file to choose.

Does somebody could help me ?

Thanks
Thomas

**Comment by mveglio** [comment]
Same question, for EHVX08S23E6V

**Comment by ronrem** [comment]
Hi guys, I have a EBVX11S23DJ9W and use the file provided in [https://github.com/raomin/ESPAltherma/issues/247](url). I'm not sure what the difference is between EHVX and EBVX. But you can give it a try.

**Comment by raomin** [comment]
I updated the file names. It should be better for finding the right definition now
