### ISSUE TITLE
Daikin Altherma MT: indoor temperature always 20°C

### ISSUE THREAD

**Issue by habitoti** [raomin/ESPAltherma#370]
The indoor temperature is constantly reported as 20°C, which is definitely not correct (or sometimes it is, though ☺️). Not that I really need that data, however I just wondered whether that is something only I am seeing or some other "hidden" problem behind that (and maybe other data is off or not current, too, then?)

**Comment by simonebortolin** [comment]
do you have the internal probe and/or madoka?

**Comment by habitoti** [comment]
No, don‘t have a Madoka. What would this reading be? I thought the temperature of the room  where the indoor unit is located (while Madoka would deliver the temperature of a heated room…)? Maybe I was just confused by the constant 20 degrees — would have expected 0 if it would be the reading of some external probe…

**Comment by simonebortolin** [comment]
is simply the default value in the absence of a makoda probe or probe

**Comment by raomin** [comment]
That clears it. Thanks @simonebortolin
