### ISSUE TITLE
Compiling errors, littefs not included, no plan how to download "feature-webui" etc etc

### ISSUE THREAD

**Issue by williwinzig** [raomin/ESPAltherma#371]
Hi Thomas,

is there a possibility that you place here a downloadableready compiled firmware? as a newbie in VSC / Platformio i don't get it done to compile a firmware without errors (the "original" roamin-firmware WITHOUT webui was not a problem to flash).

It would probably help not only me but also other beginners struggling with these problems - and as i read this was in the planning for the future ... 

This would be a really great help because i'm stuck here ..

Thanks a lot
Willi W.

**Comment by raomin** [comment]
Hello @williwinzig,

I guess your talking about #110 
This PR is not stabilized yet.
You should address this in the PR discussion. Thanks
