### ISSUE TITLE
Supports update OverTheAir

### ISSUE THREAD

**Issue by PiotrBeeScale** [raomin/ESPAltherma#415]
I'm trying to push an update to m5stickplus via OTA.

Platformio.ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
monitor_speed = 115200
upload_speed = 921600
build_flags = -D_GNU_SOURCE
lib_deps =
	PubSubClient

[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Uncomment this line to allow for remote upgrade. If name resolution does not work for you, replace with the IP of ESPAltherma
; upload_port = ESPAltherma.local
; Uncomment this line if you want to define the protocol. Autodetected otherwise.
; upload_protocol = espota

lib_deps =
	PubSubClient

[env:m5stickc]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Uncomment this line to allow for remote upgrade. If name resolution does not work for you, replace with the IP of ESPAltherma
; upload_port = ESPAltherma.local
; Uncomment this line if you want to define the protocol. Autodetected otherwise.
; upload_protocol = espota

lib_deps =
	M5StickC
	PubSubClient

[env:m5stickcplus]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Uncomment this line to allow for remote upgrade. If name resolution does not work for you, replace with the IP of ESPAltherma
**upload_port = 192.168.1.222, ESPAltherma.local**
; Uncomment this line if you want to define the protocol. Autodetected otherwise.
**upload_protocol = espota**

lib_deps =
	M5StickCPlus
	PubSubClient

build_flags = "-D ARDUINO_M5Stick_C_Plus"

[env:m5stickcplus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Uncomment this line to allow for remote upgrade. If name resolution does not work for you, replace with the IP of ESPAltherma
; upload_port = ESPAltherma.local
; Uncomment this line if you want to define the protocol. Autodetected otherwise.
; upload_protocol = espota

lib_deps =
	M5StickCPlus2
	PubSubClient

build_flags = "-D ARDUINO_M5Stick_C_Plus2"

[env:native]
# Used to run unit test; g++ must be in PATH.
platform = native
build_flags = "-std=c++11"

**Build&Upload:**

Processing m5stickcplus (platform: espressif32; board: m5stick-c; framework: arduino)
---------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/m5stick-c.html
PLATFORM: Espressif 32 (6.4.0) > M5Stick-C
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny,
tumpa)
PACKAGES:
 - framework-arduinoespressif32 @ 3.20011.230801 (2.0.11)
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - tool-mkfatfs @ 2.0.1
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 2.230.0 (2.30)
 - tool-openocd-esp32 @ 2.1100.20220706 (11.0)
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 35 compatible libraries
Scanning dependencies...
Dependency Graph
|-- M5StickCPlus @ 0.1.0
|-- PubSubClient @ 2.8.0
|-- ArduinoOTA @ 2.0.0
|-- WiFi @ 2.0.0
|-- EEPROM @ 2.0.0
|-- WiFiClientSecure @ 2.0.0
Building in release mode
Compiling .pio\build\m5stickcplus\src\main.cpp.o
Building .pio\build\m5stickcplus\bootloader.bin
Generating partitions .pio\build\m5stickcplus\partitions.bin
esptool.py v4.5.1
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Compiling .pio\build\m5stickcplus\lib8d8\SPI\SPI.cpp.o
Compiling .pio\build\m5stickcplus\lib816\Wire\Wire.cpp.o
Compiling .pio\build\m5stickcplus\lib296\FS\FS.cpp.o
Compiling .pio\build\m5stickcplus\lib296\FS\vfs_api.cpp.o
Compiling .pio\build\m5stickcplus\lib46d\SPIFFS\SPIFFS.cpp.o
Archiving .pio\build\m5stickcplus\lib8d8\libSPI.a
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\AXP192.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\Fonts\Font16.c.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\Fonts\Font32rle.c.o
Archiving .pio\build\m5stickcplus\lib816\libWire.a
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\Fonts\Font64rle.c.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\Fonts\Font72rle.c.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\Fonts\Font7srle.c.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\Fonts\glcdfont.c.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\M5Display.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\M5StickCPlus.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\RTC.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\utility\Button.cpp.o
Archiving .pio\build\m5stickcplus\lib46d\libSPIFFS.a
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\utility\In_eSPI.cpp.o
Archiving .pio\build\m5stickcplus\lib296\libFS.a
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\utility\MPU6886.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\utility\MahonyAHRS.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\utility\Speaker.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\utility\Sprite.cpp.o
Compiling .pio\build\m5stickcplus\libc18\M5StickCPlus\utility\qrcode.c.o
Compiling .pio\build\m5stickcplus\libfeb\PubSubClient\PubSubClient.cpp.o
Compiling .pio\build\m5stickcplus\libaaa\Update\HttpsOTAUpdate.cpp.o
Compiling .pio\build\m5stickcplus\libaaa\Update\Updater.cpp.o
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFi.cpp.o
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiAP.cpp.o
Archiving .pio\build\m5stickcplus\libc18\libM5StickCPlus.a
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiClient.cpp.o
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiGeneric.cpp.o
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiMulti.cpp.o
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiSTA.cpp.o
Archiving .pio\build\m5stickcplus\libfeb\libPubSubClient.a
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiScan.cpp.o
Archiving .pio\build\m5stickcplus\libaaa\libUpdate.a
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiServer.cpp.o
Compiling .pio\build\m5stickcplus\lib394\WiFi\WiFiUdp.cpp.o
Compiling .pio\build\m5stickcplus\lib272\ESPmDNS\ESPmDNS.cpp.o
Compiling .pio\build\m5stickcplus\lib247\ArduinoOTA\ArduinoOTA.cpp.o
Compiling .pio\build\m5stickcplus\lib8e1\EEPROM\EEPROM.cpp.o
Compiling .pio\build\m5stickcplus\libadc\WiFiClientSecure\WiFiClientSecure.cpp.o
Compiling .pio\build\m5stickcplus\libadc\WiFiClientSecure\esp_crt_bundle.c.o
Compiling .pio\build\m5stickcplus\libadc\WiFiClientSecure\ssl_client.cpp.o
Archiving .pio\build\m5stickcplus\lib394\libWiFi.a
Compiling .pio\build\m5stickcplus\FrameworkArduino\Esp.cpp.o
Archiving .pio\build\m5stickcplus\lib272\libESPmDNS.a
Compiling .pio\build\m5stickcplus\FrameworkArduino\FirmwareMSC.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\FunctionalInterrupt.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\HWCDC.cpp.o
Archiving .pio\build\m5stickcplus\lib247\libArduinoOTA.a
Compiling .pio\build\m5stickcplus\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\IPv6Address.cpp.o
Archiving .pio\build\m5stickcplus\lib8e1\libEEPROM.a
Compiling .pio\build\m5stickcplus\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\Print.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\StreamString.cpp.o
Archiving .pio\build\m5stickcplus\libadc\libWiFiClientSecure.a
Compiling .pio\build\m5stickcplus\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\USB.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\USBCDC.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\USBMSC.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\WString.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\base64.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\cbuf.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-adc.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-bt.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-cpu.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-dac.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-gpio.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-i2c-slave.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-i2c.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-ledc.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-matrix.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-misc.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-psram.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-rgb-led.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-rmt.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-sigmadelta.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-spi.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-time.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-timer.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-tinyusb.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-touch.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\esp32-hal-uart.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\firmware_msc_fat.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\libb64\cdecode.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\libb64\cencode.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\main.cpp.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\stdlib_noniso.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\wiring_pulse.c.o
Compiling .pio\build\m5stickcplus\FrameworkArduino\wiring_shift.c.o
Archiving .pio\build\m5stickcplus\libFrameworkArduino.a
Linking .pio\build\m5stickcplus\firmware.elf
Retrieving maximum program size .pio\build\m5stickcplus\firmware.elf
Checking size .pio\build\m5stickcplus\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  17.3% (used 56760 bytes from 327680 bytes)
Flash: [=======   ]  65.9% (used 864409 bytes from 1310720 bytes)
Building .pio\build\m5stickcplus\firmware.bin
esptool.py v4.5.1
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.
Configuring upload protocol...
AVAILABLE: cmsis-dap, esp-bridge, esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = espota
Uploading .pio\build\m5stickcplus\firmware.bin
**16:25:25 [DEBUG]: Options: {'esp_ip': '192.168.1.222,', 'host_ip': '0.0.0.0', 'esp_port': 3232, 'host_port': 25523, 'auth': '', 'image': '.pio\\build\\m5stickcplus\\firmware.bin', 'spiffs': False, 'debug': True, 'progress': True, 'timeout': 10}
16:25:25 [INFO]: Starting on 0.0.0.0:25523
16:25:25 [INFO]: Upload size: 870160
Sending invitation to 192.168.1.222, failed
16:25:27 [ERROR]: Host 192.168.1.222, Not Found**
*** [upload] Error 1
================================ [FAILED] Took 47.36 seconds ================================

Environment    Status    Duration
-------------  --------  ------------
m5stickcplus   FAILED    00:00:47.359
=========================== 1 failed, 0 succeeded in 00:00:47.359 ===========================

Environment: Windows 7
Firewall: Disabled

**I don't know what I'm doing wrong**

**Comment by PiotrBeeScale** [comment]
1. I changed the entry in the platformio.ini file
**Upload_port = 192.168.1.222, ESPAltherma.local**
on
**Upload_port = 192.168.1.222**
2. I disabled the antivirus firewall
3. I turned off the Windows firewall - public and private networks

OTA works :)

**Comment by Rudo1111** [comment]
Thanks
