### ISSUE TITLE
One parameter - one mqtt topic

### ISSUE THREAD

**Issue by rufik** [raomin/ESPAltherma#43]
Another one enhancement - send every parameter into dedicated mqtt topic, ie:
`espaltherma/ATTR/DHW setpoint` = `45`
`espaltherma/ATTR/I/U operation mode` = `OFF`

It would be helpful for selective usage/analysis :)

**Comment by raomin** [comment]
Ok, that would require quite some changes but I'll add it

**Comment by raomin** [comment]
Hi @rufik and @GO74
_Good things come to those who wait!_
Just pushed this feature, sorry if it comes late.
Enjoy :)
