### ISSUE TITLE
No readings from DAIKIN EKHBH016BA6WN year 2009 .

### ISSUE THREAD

**Issue by DDoykov** [raomin/ESPAltherma#46]
Hello,
I have tried your solution, which is great, but unfortunately the unit i am testing on is very old and esp32 cannot read it.
It has 7 pin connector. 
I connected D-Checker (ver.3.6.2.1) to it and read successfully parameters from indoor unit ( outdoor is not connected yet ).
When i monitor the connection i see that D-Checker is sending and receiving with another protocol.
Attached image shows D-Checker and serial monitoring tool.

![EKHBH016BA6WN](https://user-images.githubusercontent.com/82573519/114839572-98fdc300-9dde-11eb-8711-b9c2b7f59c72.png)

Just decided to share my information with you.
Don't know if it will be in any help for you.
Thanks.

**Comment by raomin** [comment]
Hi @DDoykov and welcome!

This serial port monitor looks nice :)

So, from what I see, it's indeed not the same protocol as the [Daikin I protocol](https://github.com/raomin/ESPAltherma/blob/main/doc/Daikin%20I%20protocol.md) (Altherma's one) but there are some similarities.

The command seems 0x02 then the register for values is 0x53 to 0x55, the CRC is probably the same.

Now what you need to do is have a look at the converters which exist in ESPAltherma and see if they apply to your protocol.
I see for ex that the `indoor suction air temp` is coded in registry 0x54 `38 0b` using the converter id 103, basically 2872/256 = 11,22.
You should find right after, `Indoor Heat Exchanger Temp,` `Outdoor air temp.` `Outdoor heat exchanger temp.` and `Discharge pipe temp`.

It should then be fairly straightforward to implement this specific definition and protocol in ESPAltherma.

Good luck! :)
