### ISSUE TITLE
After connectin m5stickc, register reading fails, keeps sending error message "check connection"

### ISSUE THREAD

**Issue by ocsele** [raomin/ESPAltherma#47]
Dear Raomin,

Please help me with this issue if you can. After turning off the heatpump (EHVX16S26CB9W, tried with ALTHERMA(LT_CA_CB_11-16KW.h did some translations but the file looks okay to me compared to the original), I connected the ESP with dupont cables (made by me from UTP cable), correct pin layout checked a lot of times, they connect to the correct I/Os:
![kép](https://user-images.githubusercontent.com/60293567/119628759-aced0980-be0d-11eb-8462-8858553d90d2.png)

The stick connects to my network, sends correctly MQTT messages, but only reports values regarding the stick itself, nothing about the heatpump itself, and the display continuously throws "timeout reading register, check connection":
![kép](https://user-images.githubusercontent.com/60293567/119629157-09502900-be0e-11eb-8a38-73a8774ffc51.png)

Can you please give me any advise on troubleshooting the issue? Already tried with another set of dupont cables (factory made, not me), to exclude wiring issues, but the result is the same unfortunately.. :( 

Thanks in advance!

**Comment by ocsele** [comment]
WOW! I'm not sure what I did, pulled off, then replugged the cables (even tested them with a multimeter, they were fine), but now it works!!!!!! Now I just have to figure out what are the useful registers for me :) Beer(s) will be sent to you Raomin for your wonderful job done here, and I'll document the setup in the other thread to show off :)
![kép](https://user-images.githubusercontent.com/60293567/119641703-386c9780-be1a-11eb-84f2-634b2ce6ade0.png)

Thanks a lot Raomin!!!!!

**Comment by raomin** [comment]
Great! Glad it works. I would have asked you to recheck your cablings anyway ;)
Thanks for your support! Enjoy!
