### ISSUE TITLE
Problems with Receiving Data

### ISSUE THREAD

**Issue by Tirocinante01** [raomin/ESPAltherma#48]
Hi everyone
I got a M5StickC on my ROTEX heating system: RHYHBH05AAV3
the Stick seems to be working but for some reason I receive no data back. The cables are attached correctly and I'm pretty confident about it but the problem persists
does anyone know what might be the problem?

**Comment by Tirocinante01** [comment]
![IMG_20210615_181105989](https://user-images.githubusercontent.com/86000254/122221839-f6cb8b80-ceb1-11eb-82e3-fd92a9342997.jpg)
![IMG_20210615_181027835_HDR](https://user-images.githubusercontent.com/86000254/122221851-f8954f00-ceb1-11eb-87c5-354afa8e8b2f.jpg)
![IMG_20210615_181132634_HDR](https://user-images.githubusercontent.com/86000254/122221862-fc28d600-ceb1-11eb-8350-e93931be2def.jpg)
![IMG_20210615_181036118_HDR](https://user-images.githubusercontent.com/86000254/122221873-ff23c680-ceb1-11eb-9fd0-54f1984b4251.jpg)


here are some images of the situation for better understanding

**Comment by raomin** [comment]
Check the cables, it's always the cables. 😉
No. Really it can only be the cables/connections. Change them if needed.

**Comment by raomin** [comment]
So @Tirocinante01, did you manage to find and fix your issue?

**Comment by raomin** [comment]
I'll close this one, feel free to reopen it if your problem is not resolved.
