### ISSUE TITLE
Finding the X10A connector

### ISSUE THREAD

**Issue by etxttul** [raomin/ESPAltherma#52]
Hi,

I have a newly installed Altherma 3 GEO 10, ESPAlterma seems to give me exactly what I want, even if my unit came with ethernet connector from start. The issue I have is that I can't find the X10A connector. Actually I can find any cirquitboards at all except the screen which you need some special tool to open. Have any one done this on the Altherma 3? If so where to find the x10A connector.

BR
Tobe

**Comment by raomin** [comment]
Hi Tobe
(copied from #53)
I didn't know this model. It seems it has a very specific board and I cannot find any reference of an X10A serial port.
So, unless you manage to find a similar port somewhere on your board and you test it for 5V to confirm it maches with a x10a, chances are you will not be able to plug in ESPAltherma. Sorry for that guys!

**Comment by KalaNagHTD** [comment]
Look at the attached pics! If you can find the main PCB „A1P“ you‘ll find the connector X10A.
![71F28283-610A-4959-B82D-FFF754258EED](https://user-images.githubusercontent.com/77481230/137619244-bebe2fc2-7cc5-46f3-a301-11df13198fae.jpeg)
![C16F0330-FE8C-4E66-87F1-7DF589776B15](https://user-images.githubusercontent.com/77481230/137619245-04aaaf56-c72a-4574-9765-b525af4f6da6.jpeg)
