### ISSUE TITLE
 I do not receive all the attributes in Home Assistant

### ISSUE THREAD

**Issue by frodix** [raomin/ESPAltherma#54]
Hello, I am trying to use this project. I have an Altherma EHVX16S26CB9W.

I have a problem, my Home Assistant only receives the attributes that start with 0x00. The other attributes that start with 0x10, 0x11, 0x20 ... are not received through mqtt and they do not appear to me as attributes.

![image](https://user-images.githubusercontent.com/27883894/138065659-402d9cfc-b2eb-4f0b-954a-7abffe51a860.png)

![image](https://user-images.githubusercontent.com/27883894/138066081-47952381-4800-400d-babf-84e9be033f87.png)

I’m using Esp32, and I have HA version core-2021.10.6 and Mosquitto broker version 6.0.1.

Sorry for my English but I'm using Google Translate, I'm from Spain.

what could be the problem?

Thank you!

**Comment by raomin** [comment]
Tell us one thing: how is powered your ESP32?
If it is with a separate USB power supply, make sure to still connect the GND of the ESP32 to the one of the X10A port.
Suerte ;)

**Comment by frodix** [comment]
Finally I tried with another esp32 and i already get data.
Although some attributes like {0x20,0,105,2,1, "Outdoor air temp. (R1T)" or {0x21,0,105,2, -1, "INV primary current (A)"} I get 0.
I guess it will be the fault of my machine.
Thank you!

**Comment by raomin** [comment]
Yes indeed, some machines do not return the current consumption...
Have fun!
