### ISSUE TITLE
Adjust temperature offset

### ISSUE THREAD

**Issue by fredilarsen** [raomin/ESPAltherma#55]
I recently upgraded the MMI firmware of my Altherma 3 to version 1.7.0, and the Residential Controller app now allows me not only to turn the pump on/off as before, but to adjust the flow temperature offset. I have the LAN adapter.

Does this mean that changing the offset could be possible with ESPAltherma as well?

Adjusting the offset would be ideal for adjusting to varying electricity prices. Could let HA lower the offset when prices are especially high, and increase the offset when prices are low. This allows for more granular control than just asking the LAN adapter to turn the pump off as I currently have it configured.

**Comment by raomin** [comment]
Hi @fredilarsen,
ESPAltherma does not control any values of the heat pump. Unfortunately, we have not yet found a way to control the HP through the X10A port. The LAN adapter is a gateway between some values and the P1P2 communication bus, which is the standard way for setting values.

Personally, I chose to control myself when the HP should heat and when it should not.
I have a [climate entity](https://github.com/raomin/ESPAltherma#a-climate-entity) and an automation to adjust the target temperature depending on electricity price. Ok, it's not the water flow temperature, but that tends to heat when it's cheaper.

**Comment by fredilarsen** [comment]
Thanks for the feedback.
I have set up an automation that uses a relay to tell the LAN adapter to deactivate the Altherma when the highest electricity price peaks occur. I was just thinking of ways to improve that.

With the LAN adapter setting the temperature offset when I adjust it in the app, I could potentially monitor the P1P2 bus to log what is sent when doing this. I have some P1P2 related chips from when I first planned doing this but did not have a good enough starting point.

I was asked to provide direct feedback on the Altherma in the app, not to google play store but to Daikin, so I gave them a wish about opening the API so a Home Assistant integration can be made.

**Comment by raomin** [comment]
As you understood, with ESPAltherma, the idea is more not to rely on the LAN adapter.
The automation with the relay to turn on and off is supported with ESPAltherma ([here](https://github.com/raomin/ESPAltherma#step-3-optional---controling-your-daikin-altherma-heat-pump))

You might be interested in looking at the SmartGrid discussion we had here: #3 
I still need to find some time to play with the X85A port. That would add some smartgrid capability (mainly adjust power consumption with electricity cost) to ESPAltherma...!
