### ISSUE TITLE
Problem with visibility of variables in HA

### ISSUE THREAD

**Issue by TomaszCwik** [raomin/ESPAltherma#57]
Hello,
I have problem with integration ESP with HA
in this moment when i giving ip address of HA in MQTT explorer  i see 3 record LWT,LOG,ATTR 
![image](https://user-images.githubusercontent.com/34006184/140584921-e8a9b9d7-2e32-4f4c-9055-c67bbc3fd886.png)
but in HA i see only 
![image](https://user-images.githubusercontent.com/34006184/140584993-b6090f90-79a1-41ca-95c7-f1d127693ac6.png)
i use ESP32 with external Power suplly 
in setup.h i uncomment #include "def/DEFAULT.h"

**Comment by TomaszCwik** [comment]
in MQTT info in HA i see:
![image](https://user-images.githubusercontent.com/34006184/140645606-8899264d-a24d-423f-8c23-69c305796570.png)
in ATTR i always have "}"
in setup.h:
![image](https://user-images.githubusercontent.com/34006184/140645679-a6929341-cbdc-40b7-95d4-85586146e114.png)
![image](https://user-images.githubusercontent.com/34006184/140645661-0984cd8f-1370-416c-8ec3-1e0d5a449f68.png)
in default.h
![image](https://user-images.githubusercontent.com/34006184/140645693-77458fa3-12fb-4371-87ca-a864b165fd64.png)
IN HA i have information about wrong JSON

**Comment by raomin** [comment]
Can you show us what pops under espaltherma/LOG or show what is coming up on the Serial monitor?

Are you sure the grounds of your Esp32 is linked with the ground of the heat pump?

**Comment by TomaszCwik** [comment]
That's it ...
i didn't connect GND with "-"
i`m sorry : P

**Comment by raomin** [comment]
Good to hear it's now working for you.
I'll emphasise on this in the readme.
