### ISSUE TITLE
Logic level converter?

### ISSUE THREAD

**Issue by Gollam** [raomin/ESPAltherma#64]
We have an Altherma 3, and I'd like to include a logic level converter in my setup, because it's very cheap, so why not. I am just wondering, is this the correct setup if one would like to use it?

![image](https://user-images.githubusercontent.com/765342/142628670-a52c4b04-4867-411a-b258-70fa5dd9bf8c.png)

**Comment by raomin** [comment]
Hi @Gollam, I think no one ever implemented it. Now, if you really want to do it, yes that should be the way to go.

**Comment by Gollam** [comment]
@raomin Thanks!

**Comment by Gollam** [comment]
@raomin BTW, how can it be determined what levels a given interface uses? I haven't found any documentation about X10A and I'm just curious.

**Comment by raomin** [comment]
Usually, it uses the VCC you can find in the port ;)
So here +5V. If you want to be sure, you need a oscilloscope.
