### ISSUE TITLE
Possible to use NodeMCU CH340?

### ISSUE THREAD

**Issue by 5G7K** [raomin/ESPAltherma#65]
Hello,

great project! I want to test if it works for me, too.
I have several NodeMCU CH340. Example: https://www.makershop.de/plattformen/esp8266/nodemcu-esp8266-dev-kit/
I don't have experience with paltformio...
Does the project support NodeMCU?

Build process works fine. But Upload not. Error 2

I tried it with a new empty project with board type NodeMCU 1.0
Build & Upload works fine

Then I tried to add NodeMCU to your project
Create new project - same name, board NodeMCU 1.0
Is this the correct way?
Now Build process stops with message: fatal error: WiFi.h: No such file or directory
Nothing found in the web which really helps me.

Can anybody help?

BTW: I had to change comm.h lien 26 to   MySerial.write(prep);. Otherwise build did not run

Thank you very much!
Andreas

**Comment by raomin** [comment]
Hi @5G7K, thanks for your appreciation.
ESP8266 is not supported for hardware reasons, see here: #14 
Get an esp32 for christmas! :)
