### ISSUE TITLE
Power usage during defrost operation 

### ISSUE THREAD

**Issue by niekveldhuizen** [raomin/ESPAltherma#69]
Hi,

I have build my ESPAltherma with an M5StickCPlus, everything is working as it should. But now it is getting colder and the unit starts more defrost cycles during heating.

When the defrost start the primary inv current drops to 0, but in my P1 meter i can see that is peaks from 4Kw up to 9kw. Defrost cycle takes about 5 min.  But it is not counted in my total for the day for the heatpump. 
How can i achive this?

**Comment by KalaNagHTD** [comment]
These are the data my unit logs during defrost:

![EA6C39C4-FC6B-4F52-AFD4-2E88F3F7311E](https://user-images.githubusercontent.com/77481230/144026050-cdd19280-adcf-4922-8914-ee7dc40dbcb8.jpeg)

**Comment by niekveldhuizen** [comment]
I use Home Assistant to log everything. I used my P1 data to measure the kwh spent during the 4/5 minutes of defrost and i averages about 0.4kwh for a defrost cycle. But the primary inv (A) does not reflect this so my logging for the usage of the heatpump total kwh for the day is missing the defrost cycle

**Comment by KalaNagHTD** [comment]
So something is wrong with your primary current data…

**Comment by niekveldhuizen** [comment]
Yeah i dont know. the normal heating proces is registerd just fine. It looks like the defrost is is not using the primary inv. But somtething like the heating element in the DHW tank (that is 9kw) but i do not se a register for that value

**Comment by raomin** [comment]
I'll close this one. Open a discussion if still not clear
