### ISSUE TITLE
Can I use this with EKHHP300AC2V3?

### ISSUE THREAD

**Issue by joseal** [raomin/ESPAltherma#70]
Hi I've an EKHHP300AC2V3 heat pump and I'm looking for a way to connect it with my home assistant.

![image](https://user-images.githubusercontent.com/24917156/144776697-29e076b3-79e0-4e14-a872-72940983beca.png)

With this board:

![image](https://user-images.githubusercontent.com/24917156/144776818-1fac2d54-8599-4682-9732-acf61f670547.png)

Could you please confirm if anyone has this code working with this model of pump?

**Comment by KalaNagHTD** [comment]
It‘s a DHW heatpump w/o space heating function. As long as it provides the Daikin X10A service connector there is a good chance you can draw lots of useful data. Give it a try!

Karl

**Comment by joseal** [comment]
Thanks @KalaNagHTD. I have a few Esp32 and I am going to try. Do you know where are the 5v on this 8pins connector?

**Comment by robsonke** [comment]
https://github.com/raomin/ESPAltherma#8-pin-x10a-connection

**Comment by KalaNagHTD** [comment]
![F8BEF887-7697-41B3-A899-62724A6D50D2](https://user-images.githubusercontent.com/77481230/144847178-cde376a0-d101-4a39-97ef-6e0c984ffeca.jpeg)

**Comment by joseal** [comment]
Thank you!

**Comment by joseal** [comment]
Hi @KalaNagHTD,

I've compiled the code for board esp32doit-devkit-v1 (as I'm using the ESP32 Wroom) and using both default.h and def/ALTHERMA(LT_MULTI_DHWHP).h, but I'm not able to comunitcate with unit.

This is what I see in console:

![image](https://user-images.githubusercontent.com/24917156/145566834-21d38e4e-95c0-4a36-a010-ec283de00a38.png)

The cable is ok (tested the connection to the board) and the ESP32 is sending data on serial 2 (tested with an RS232 adaptor setup for 9600 8E1) and I've already swapped the TxD and RxD (just in case).

So, I'm not sure what I'm missing.... Any ideas?

**Comment by KalaNagHTD** [comment]
The Daikin diagnostic software D-Checker (Windows) uses the same connector and data. I would give it a try!
[D-Checker](https://www.thermalsupplyinc.com/daikin-service-checkers/)

**Comment by andreapier** [comment]
I had a similar issue (#51) and it turned out to be a grounding problem. Check you ground connection and make sure you are following @raomin advise in README.md:
> Whatever you do, make sure you keep a wire connecting the GND of the ESP32 to the GND pin of the X10A (even if you power your ESP32 with a USB charger)!!

**Comment by raomin** [comment]
This one is pretty weird (too). The ESPAltherma is reading what it is sending...
Sending 0x03 0x40 0x61 0x5b is a query for register 0x61, but it reads back exactly the same... As if RX was linked to TX or if there was an echo somewhere...
Please check once more your wiring and remember that your RX on the ESP32 must be linked to TX. Same for TX to RX...

**Comment by joseal** [comment]
Hi All,
I've already review and tested the wires multiple times and I'm not finding any issue...
Also, I'm getting this response, even when I swap the TxD with RxD...
To be honest, I'm a bit without ideas, but I'm going to follow @KalaNagHTD 's suggestion and see if D-Checker shows something.

thank very much All for your support so far!

**Comment by joseal** [comment]
@raomin, I just noticed this on the mqtt side:

![image](https://user-images.githubusercontent.com/24917156/145690585-1db643e6-c19c-44a0-805c-d2bc308fffe2.png)

Do you know what it means this 0x15 0xea?

**Comment by joseal** [comment]
In the meantime, I've found a comment on another forum, saying that the 0x15 0xea is the typical answer (from the pump), when the last query was not understood.

If this is the case, I believe we can assume that the wires are good (as we have the right answer from the pump).

Also, having a clear 0x15 0xea answer, it probably means that the com port speed and setup should be good, right?

**Comment by raomin** [comment]
0x15 is indeed an error code.
But you might still read properly an error response if your parity is wrong. You can check (as I was also suggesting in this other forum) to change your parity, maybe this unit had a different one...

**Comment by joseal** [comment]
> 

Just tried the following combinations, without success:

  MySerial.begin(9600, SERIAL_8E1, RX_PIN, TX_PIN);
  MySerial.begin(9600, SERIAL_8O1, RX_PIN, TX_PIN);
  MySerial.begin(9600, SERIAL_8N1, RX_PIN, TX_PIN);

**Comment by raomin** [comment]
Really @joseal, I'm out of idea. Maybe last chance would be to try with DChecker as @KalaNagHTD suggested. If it work there, then there might be some protocol specificities. Then if you have a serial monitor you can see what changes...

**Comment by dncex** [comment]
just a possible hint: how long are the cables? If you receive what you transmit, it might be a crosstalk problem. Double check the ground connection too

**Comment by joseal** [comment]
Thank you both, I'm going to build a new cable, just to eliminate any chances to be the cable. @dncex could you please elaborate a bit more about that issue?

**Comment by joseal** [comment]
Ok, I've tested it with a new cable (with coaxial ground, just to make sure it wasn't noise), but no changes:

![image](https://user-images.githubusercontent.com/24917156/147139150-21258aca-fc8a-4725-9d5b-11f8f3a61828.png)

I've also tried the service checker type 4 tool, but it also fails doing the maps....

Do you know about anyone with the same model as me, that was able to communicate with the unit?

thank you very much for your support!

**Comment by ruislv** [comment]
Hi @joseal,
i'm facing a similar issue with 500L version. By any change you came to a conclusion or what other findings you got so far?
tkx
r.

**Comment by joseal** [comment]
Hi Rui,
unfortunately, I was not able to find why the x10 port is not working as expected in my heat pump.
Maybe this model has a different board/protocol...
I'm trying to find someone that has the original technical interface, in order to test the port.
It was nice to know if someone else with these models were able to make it work...
thank you,
Jose

**Comment by maps2002** [comment]
Hi there.

I have the same heat pump model, and the results are the same.
I also have a USB to TTL adapter that I can try to use with DChecker to capture the protocol.

But before I do something wrong, can someone (@raomin ?) advise me/confirm how the connections should be like?
 - TX/RX (X10A) ->  RX/TX (TTL)
 - GND (X10A) -> GND (TTL) (because of the common ground?)
 - No other pin connection is necessary (TTL receives power from the computer)

Thanks in advance

**Comment by raomin** [comment]
Yes @maps2002, your connection is correct.
GND-GND is essential.

**Comment by maps2002** [comment]
Thanks for the feedback.
Tried with service checker 4, but had the same result as @joseal .

So it seems that until the "right" service check is found, it won't be possible to reverse the protocol and support this model :|

**Comment by raomin** [comment]
@maps2002, the protocol on this old one is most probably the S-Protocol that has been included in ESPAltherma last month.
I added some info on README. Give it a try!

**Comment by joseal** [comment]
@maps2002 did you had chance to try the S-Protocol on yours?

**Comment by maps2002** [comment]
Hi @joseal and @raomin, tried with the S-Protocol. Definitely works!
With PROTOCOL_S_ROTEX definition file (not with PROTOCOL_S), the "DHW tank temp.(C)" and "Refrig. Temp. liquid side(C)" seems to be read properly. All the other values don't seem to contain any valid data that I can relate with anything.

This DHW only heat-pump is from this year. Not-old, but it seems it uses PROTOCOL S none the less.

Maybe more registers can be queried, but at this point not sure what to try/test.

**Comment by joseal** [comment]
Hi @maps2002,
thank you very much for the update. Fantastic news! I'll refresh the repo and give it a try later today or tomorrow to see if I can somehow help you find more registers. Let's keep in touch.

**Comment by andrepcg** [comment]
I also have a EKHHP300AC2V3 and it works with `PROTOCOL_S_ROTEX`.

```
Circulation pump: OFF
External heater?: OFF
Priority to domestic water: OFF
Burner inhibit from solaris: OFF
Refrig. Temp. liquid side(C): 32.75
Inlet water temp.(C): 212.953
Outlet Water Temp.(C): 212.953
D(C): 212.953
DHW tank temp.(C): 48.5
F(C): 0.00390625
Delta-Tr(deg): 0
R/C Setpoint(C): 0
Operation Mode: Fan Only
Error Code:  0
Thermo Off Error:  0
Warning Code:  0
Caution Code:  0
????: -69.5547
WifiRSSI: -58dBm
FreeMem: 24216
friendly_name: ESPAltherma AlthermaSensors
```

`DHW tank` and `Refrig. Temp. liquid side(C)` are temperatures for what the manual says it has sensors for, although the labels are a bit off:
<img width="462" alt="image" src="https://github.com/raomin/ESPAltherma/assets/405387/a29c1eb1-4e66-4f08-95bd-37457257184b">

`External heater?` turned ON when the booster-heater (BSH) was activated. Would be cool to figure out what other values and labels we have available for this unit
