### ISSUE TITLE
Possible to control power heating?

### ISSUE THREAD

**Issue by StoricU** [raomin/ESPAltherma#72]
Hi,

I have an Altherma 3, and was just wondering if there is a simple way turning on power heating with this solution?
Or is there any other way to control power heating with Home Assistant or MQTT?

**Comment by raomin** [comment]
Hi @StoricU,

Yes, ESPAltherma can simulate a thermostat.
Please see https://github.com/raomin/ESPAltherma#step-3-optional---controling-your-daikin-altherma-heat-pump
On the same page, you also have configuration details on how to setup a thermostat entity on Home Assistant.
