### ISSUE TITLE
Freeze/crash issue?

### ISSUE THREAD

**Issue by Gollam** [raomin/ESPAltherma#73]
I have had my m5stickcplus running for a month without issues, then suddenly 2 days ago it started going offline, and it has been like that since a day now. I'll take it out and reset it in the afternoon, but do you have any idea what should I check?

![image](https://user-images.githubusercontent.com/765342/146666742-1f0c7ec5-5758-4daf-b5d7-0c7c93aa2791.png)

**Comment by stomko11** [comment]
Happened to me twice. Like you said, month or so without single issue, then one day 9:00 am sharp, esp (m5stickc) was dead. Pulled 5v input, put it back, All worked. Hour later, same thing. Did that procedure again, and all is working now since then (that was about a week ago)

**Comment by raomin** [comment]
Hi! 
That's weird, I don't see what could happen. 
Never had any issue, mine has been running for a year now (!). I've had more general issues with my WiFi or dhcp overlapping with ESPAltherma but that's all.
Best would be to log the ~/Log topic somewhere and see if something happens...

**Comment by Gollam** [comment]
Now I took it apart. The screen of the stick said: Restoring previous state: Off Setting up Wifi... Connecting to XXX and nothing else was happening.

**Comment by raomin** [comment]
Then probably the WiFi is unreachable or it's dhcp not responding... Check in a different location closer to the access point.

**Comment by andreapier** [comment]
This happens to me too from time to time but I have never been able to understand what is going on exactly. I do not think it is a wifi issue as my AP is next to ESP

**Comment by stomko11** [comment]
In my case, when that happened, there was nothing on the display. No reaction to any buttons. Pulling 5V and connecting it again immediately resolved it. Unfortunately I do not have any logs from that time to help narrow down the issue.

**Comment by Gollam** [comment]
Happy New Year! I discovered that if I leave it running long enough, it will eventually return to normal state. Maybe sometimes the wifi drops it, in that case router restart triggers the restore. And other times maybe HA restart solved it. I'm still trying to determine the exact cause.

**Comment by raomin** [comment]
This issue gave me an idea, I've added the wifi signal strength as a sensor value.
This might help identifying wifi issues...

**Comment by Gollam** [comment]
I installed a wifi repeater nearby the device, and so far, I had no large outages. Now I only have very small, max 30 minute ones. So I think that helped.
