### ISSUE TITLE
Smart Grid Pins locations

### ISSUE THREAD

**Issue by vekexasia** [raomin/ESPAltherma#81]
Hello, 

I just discovered this project and read almost all issues, In the main readme there is a mention on J8 connector to leverage smartgrid functionalities.

Since i'm a rookie i couldn't find any reference to the location of such connector on my machine. I took a picture of it:

![image](https://user-images.githubusercontent.com/200523/154041057-bf974e9c-77e9-47bc-ab7a-badd62190556.png)

PS: my model number is: Daikin Altherma 3 R ECH20 - EHSXB08P50DA which does not have a perfect match on the include files (according the models listed in the wiki pages). But i believe is ALTHERMA(HPSU6_ULTRA).h. 

Another question. Assuming I can find the j8 i would also need the 2 relays to use. any suggestion on good ones? PS: I'd be using the m5stack atom lite esp32 dev board https://shop.m5stack.com/products/atom-lite-esp32-development-kit

**Comment by KalaNagHTD** [comment]
![Uploading E9199770-CF3A-4198-8828-C011ABA9EB97.jpeg…]()

**Comment by KalaNagHTD** [comment]
![D895C544-321B-481F-9E4F-D3343ED82EB5](https://user-images.githubusercontent.com/77481230/154046566-78ed527a-4015-491b-b09d-744ac513672d.jpeg)

**Comment by vekexasia** [comment]
<3

**Comment by andreapier** [comment]
I recently purchased [this 2 channels relay module](https://www.aliexpress.com/item/1005001725711302.html?spm=a2g0o.order_list.0.0.21ef1802jb7TBb).
It works fine, but I will wait a bit more time before commenting on how good (or bad) it is.
About the board you want to use, just make sure it has a GND GPIO or you might experience weird issues reading values from your heat pump.

**Comment by raomin** [comment]
Just keep in mind that the voltage of ESP32 GPIOs is 3.3v, usually this is enough to power the opto couplers on these module, but I would recommend to get a 3.3v model.
I'm closing this issue as the answers have been provided by @KalaNagHTD and @andreapier 
but feel free to comment on it with your progress.

**Comment by ocsi01** [comment]
@vekexasia Did you managed to run this on the `m5stack atom lite`? I just got the ´[AtomS3 Lite](https://shop.m5stack.com/products/atoms3-lite-esp32s3-dev-kit)´, but facing some issues deploy it.
