### ISSUE TITLE
Nomenclature Help

### ISSUE THREAD

**Issue by vekexasia** [raomin/ESPAltherma#82]
![image](https://user-images.githubusercontent.com/200523/154327664-7fad8fed-f02f-4f01-be3e-3e887a5b0f38.png)

Hello guys, Today I successfully integrated with X10A. Since I'm no expert in this field i might be missing some names:

 - DHW -> domestic hot water
 - R1T - R2T etc? 
 - RT Temp?
 - LW?
 - BUH?

:)

**Comment by raomin** [comment]
Hi @vekexasia 

R1T, R2T etc. are conventional names for specific temperatures in the circuits of external or internal unit. But the definition is in the name.
RT Temp is the return temperature when it comes back from your house to the heater.
LW is the target temperature from your water logic (function of the external temp)
BUH is backup (electric) heater.

You'll find some info there (and can contribute too! :) )
https://github.com/raomin/ESPAltherma/wiki/Information-about-Values
