### ISSUE TITLE
error 22 - bat vol error check hardware

### ISSUE THREAD

**Issue by crounauer** [raomin/ESPAltherma#83]
I have ordered 2 M5Stick C and both have an error code "error 22 - bat vol error check hardware" when first plugged into usb-C. I have tried charging them overnight but still the same error appears. Does anyone have a suggestion to fix this error?
Thanks ;)

**Comment by qris** [comment]
Have you seen [this article](https://community.m5stack.com/topic/2130/error-22-bat-vol-error/11)?

**Comment by crounauer** [comment]
Hi qris,
Yes, I've tried all those options.
Thanks for your reply.
Cheers!

**Comment by raomin** [comment]
Hello @crounauer 
I'm sorry to hear that, but it's unlikely that this is the best place to find help for that.
But is it preventing you from programming the esp32?

**Comment by crounauer** [comment]
Hi Roamin,
Yes, it's not possible to get past the error message.
I'll order from another shop, maybe it's old stock?

**Comment by crounauer** [comment]
Would this ESP32 board work? => ESP32 Development Board BLUETOOTH WIFI - ESP-WROOM-32 Arduino Raspberry PI IoT

**Comment by raomin** [comment]
Have you tried to open the m5 and disconnect the battery?
If still not working, yes any esp32 would work. Its just that m5 has few advantages (magnetic, screen...)
You can get a m5stickc plus, it shall be fresher...

**Comment by crounauer** [comment]
That's a great idea, why didn't I think of that? Nothing to loose, I'll give that a try tomorrow. Thanks.

**Comment by raomin** [comment]
I'll close this one, I hope you solved your m5 issue...
