### ISSUE TITLE
no data in homeassistant

### ISSUE THREAD

**Issue by onix20** [raomin/ESPAltherma#84]
Hello,
I have installed the m5stackcPlus on my Daikin Althema 3 Geo.

On my  Notebook I see all data come in:
![grafik](https://user-images.githubusercontent.com/41266602/155898398-0654203d-9bc6-46a1-bcaa-d95fb8b784ec.png)

in the protocoll from mqttt mosquito I see this:

![grafik](https://user-images.githubusercontent.com/41266602/155898493-db10f221-71dc-42c5-85a8-8faea54f712e.png)

on listenning mqtt broker I see only data from espaltherma/config:

![grafik](https://user-images.githubusercontent.com/41266602/155898617-5399a8da-9724-4679-b5a6-0bd9d34f1920.png)

All other data from espaltherma/log I see nothing:

![grafik](https://user-images.githubusercontent.com/41266602/155898696-4f1bd6a7-4e2b-4ac3-b72e-930f936fa5a0.png)

In HA I see only this:
![grafik](https://user-images.githubusercontent.com/41266602/155898786-207805f5-2712-484f-8571-713f6b1467c7.png)

What is the issue?

**Comment by raomin** [comment]
Did you fix it?
