### ISSUE TITLE
2 Zones problem 

### ISSUE THREAD

**Issue by ablyes** [raomin/ESPAltherma#87]
Is this project bringing more than what the lan adapter can do ? 

i’m specially thinking about the 2 zones problem: we can’t control 2 zones (or areas) with the l’an adapter. 
I don’t know if it’s a deep limitation in the Daikin Altherma or just because of the madoka/lan adapter. 

Thank you for the help.

**Comment by raomin** [comment]
Hi @ablyes, I don't know about the LAN adapter, but I've been told, ESPAltherma gave more information than the LAN adapter.
As for the 2 zones control, I believe that you can use 2 relays to simulate thermostats for each zone. That will be basic ON/OFF control but this is just what I need as I control the temperature with Home Assistant.
