### ISSUE TITLE
unknown value

### ISSUE THREAD

**Issue by Krinou3000** [raomin/ESPAltherma#88]
Hi and great job @raomin !

I install an M5StickC Plus on my EHVH04S18CB.

But I have often some `unavailable` values on the AlthermaSensors entity and this cause at the same time `unknown` values for the sensor.templates I created.

I don't know exactly why. Sometimes I don't have this issue for several hours .
Wifi signal seems good with router (WifiRSSI -58dBm).

![espaltherma1](https://user-images.githubusercontent.com/50716259/159093797-9627d058-15eb-48ab-85bb-71e1386eca34.jpg)

**Comment by raomin** [comment]
Hi @Krinou3000 
That's probably network/wifi connectivity issue. We you observe this behavior, do you manage to ping the m5?

**Comment by Krinou3000** [comment]
Yes, you right. I test with the esp a little more outside the case and I put the antennas of the router straight.
 I no longer have any data reception cut off.

**Comment by Krinou3000** [comment]
Now, I have this ping result. I don't know if it's good or not for the M5StickC

```
Envoi d’une requête 'Ping'  192.168.2.242 avec 32 octets de données :
Réponse de 192.168.2.242 : octets=32 temps=49 ms TTL=255
Réponse de 192.168.2.242 : octets=32 temps=356 ms TTL=255
Réponse de 192.168.2.242 : octets=32 temps=256 ms TTL=255
Réponse de 192.168.2.242 : octets=32 temps=81 ms TTL=255

Statistiques Ping pour 192.168.2.242:
    Paquets : envoyés = 4, reçus = 4, perdus = 0 (perte 0%),
Durée approximative des boucles en millisecondes :
    Minimum = 49ms, Maximum = 356ms, Moyenne = 185ms
```

**Comment by raomin** [comment]
Your pings speed jitters a lot (from 49ms to 356), that's not good for your network.
But this might be "good enough" for ESPAltherma. If you still have unknown values, you can also leave the M5 outside the heatpump... Also, personally, I did not replace the metallic plate to avoid faraday cage effect...
I close the issue, reopen it if you have news!
