### ISSUE TITLE
Wrong voltage and pressure

### ISSUE THREAD

**Issue by rayxxxxx** [raomin/ESPAltherma#90]
First of all, @raomin, Wonderfull job!!!
I installed ESPAltherma in my Altherma 3 H HT ECH2O and it works.
But there are some wrong data (I think).
0x21,4,101,2,-1,"Voltage (V)" give me a value higher than it can be. ESPAltherma reads values between 450 and 500 but it should be 230-250. I've got a Shelly EM and it returns 245 V. I tried 0x21,2,101, however that returns always 0.
{0x20,14,105,2,2,"Pressure"}, {0x62,11,105,1,2,"Water pressure"}, {0x62,15,105,2,2,"Pressure sensor"} never return 2.3 bar.
Can you help me?

Daikin Models: ETSX16P50D, EPRA14DAV3
ESPAltherma with M5STickCPlus (Default.h or ALTHERMA(HPSU6_ULTRA).h)

**Comment by raomin** [comment]
Hi @rayxxxxx, thanks for your support (and the beer :))
Some models do not have a voltage sensor (you'll find previous issues on this) (just put 245 in you CoP calculation).
But I recall no one without a pressure value... Have a look here https://github.com/raomin/ESPAltherma/wiki/Information-about-Values and try all other "pressure" values.

**Comment by stomko11** [comment]
I wonder about that pressure to. I have manometer on the heatpump that shows 1 bar pressure (that is pressure in circuit - water heating or DHW). Is that the pressure we are talking about? Also, heatpump does not show that value (or any other pressur value) in control unit.
I tried querying all the values, neither returns values around 1 or 14,5 which would be equivalent in PSI.
```
TESTP1-High Pressure: 10.7
TESTP2-High Pressure(T): Conv 405 not avail.
TESTP3-Low Pressure: 8.6
TESTP4-Pressure sensor: 8.6
TESTP5-Pressure: 8.6
TESTP6-Low Pressure(T): Conv 405 not avail.
TESTP7-Pressure sensor(T): Conv 405 not avail.
TESTP8-Pressure(T): Conv 405 not avail.
TESTP9-Water pressure: 0
TESTP10-Refrigerant pressure sensor: 0
TESTP11-Pressure sensor: 0
TESTP12-Refrigerant pressure sensor: 0
```

**Comment by raomin** [comment]
I will code the 405 converter so you can see the missing values

**Comment by stomko11** [comment]
Thank you. Then I should be able to see the pressure?

**Comment by raomin** [comment]
You will get some values where there is "Conv 405 not avail.". Not sure that will be the right value...

**Comment by raomin** [comment]
I looked at the 405 converter, it basically gives the temperature of the refrigerant gaz (eg R32) in the compressor. So not what you're looking for. But I coded it anyway.

The water pressure should be on this value:
`{0x62,11,105,1,2,"Water pressure"},`
It's a registry that is constant on 18 definition files. So I'm pretty sure it's the right one.
Could be that you have a defective pressure sensor on the HP... Do you see a coherent value on the user interface of the HP?

**Comment by rayxxxxx** [comment]
The user interface of the HP shows 2.2 bar and it's a coherent value (I think, I'm a simple user).

**Comment by stomko11** [comment]
@raomin no, my heatpump does not show any pressure values anywhere in the user interface. I only have analogue manometer that shows the pressure.

**Comment by raomin** [comment]
Then it is most probably not monitored and the reason why water pressure returns 0...
Sorry

**Comment by stomko11** [comment]
@raomin I only got to it now, and actually realized I can see pressure value in your readings
`{0x20,14,105,2,2,"Pressure"},`
This shows now 12.5 which is in PSI, and I have been looking for value corresponding to bars, which is what I see as main unit on analogue manometer. But psi is right there too, 12,5 =~ 0.86 bar

**Comment by rayxxxxx** [comment]
@stomko11  Not in my case. {0x20,14,105,2,2,"Pressure"} shows 12.5 but Daikin display shows 2.2 bar

**Comment by stomko11** [comment]
@rayxxxxx right, I may have spoken too soon. Even if I added water to curcuit and pressure elevated to 1.4bar, the value (after calculation) is between 0,86-0,99 so it is not that. What a shame :-(

**Comment by RodEzIO** [comment]
same problem here, I am trying to read the pressure to debug an hydraulic problem but I can't get any useful value. My altherma is an EHSX08.
