### ISSUE TITLE
Rotex HPSU 508 Compact  ESP32

### ISSUE THREAD

**Issue by Micha031982** [raomin/ESPAltherma#91]
Hi,

i tried different things to get this working but failed.

Setup:
Rotex HPSU 508 Compact
used can J13 anfd Ground from here
![image](https://user-images.githubusercontent.com/19914654/159923015-10650243-ff8d-4b5f-aebc-1bd2f623513f.png)

 ESP32 with usb power (ESP-32 Dev Kit C V2)
Pin 16/17

Setup with the same like here in a other Post
#include "def/ALTHERMA(HPSU6_ULTRA).h"
and the same parameters like in the other poste
https://github.com/raomin/ESPAltherma/issues/45

Tries:
different Ground on ESP
Different directions of can
ground to all grounds of the ESP
2 sets of jumper cable
second ESP

What i get:
![Screenshot 2022-03-24 120041](https://user-images.githubusercontent.com/19914654/159923522-1d7e0e4e-ca5d-4091-a52b-ec06c99db2c3.jpg)
![Screenshot 2022-03-24 134116](https://user-images.githubusercontent.com/19914654/159923609-893cbacf-bec7-48a2-90a5-a6236ad1fa62.jpg)

Any idea what i can try additionaly?

**Comment by raomin** [comment]
Do I read you well? You connected ESPAltherma on the CAN bus??
Err... ESPAltherma is supposed to be connected to the serial port X10A, not the CAN bus...

**Comment by Micha031982** [comment]
Thanks for the quick answer
Works now (had mixed up this manual with those for FHEM)
