### ISSUE TITLE
How can i automate thermostat and SG relay?

### ISSUE THREAD

**Issue by colseven** [raomin/ESPAltherma#92]
Hello again :)

last question, i installed the relay for the thermostat and smart grid and can also control them - it all works. but if i build an automation then i can't select and automate the devices. where is my mistake??

this did not work
`type: turn_on
entity_id: switch.sg_altherma
domain: switch
`

configuration.yaml
`switch:
  - platform: mqtt
    name: SG Altherma
    state_topic: "espaltherma/sg/state"
    command_topic: "espaltherma/sg/set"
    payload_on: "2"
    payload_off: "0"`

Thank you very much.

![bild 2022-03-25 um 10 15 08](https://user-images.githubusercontent.com/63189272/160091795-9d3f59a9-554d-4aab-b7af-793504db1454.jpg)
![bild 2022-03-25 um 10 15 21](https://user-images.githubusercontent.com/63189272/160091804-28cfa546-ac1c-4c88-9699-8322c3568472.jpg)
![bild 2022-03-25 um 10 16 05](https://user-images.githubusercontent.com/63189272/160091811-a8c59d0f-9d29-4dce-a3f4-bb5d7e0a9845.jpg)

**Comment by colseven** [comment]
solution

`type: turn_on
device_id: Altherma
entity_id: switch.altherma
domain: switch`

`type: turn_on
device_id: SG Altherma
entity_id: switch.sg_altherma
domain: switch`

**Comment by raomin** [comment]
Yup! You got it! :)
