### ISSUE TITLE
EHVX 16S18CA3V

### ISSUE THREAD

**Issue by fmateosf** [raomin/ESPAltherma#93]
Hi!
I have an Altherma EHVX 16S18CA3V.
It works great, but I cant find de right configuration file for this model.
¿Some one whith the same model or similar can help me?

Thanks!

**Comment by raomin** [comment]
For more info have a look here: https://github.com/raomin/ESPAltherma/wiki/Choosing-the-right-definition-file 
Try this one ALTHERMA(LT_CA_CB_11-16KW).h

**Comment by fmateosf** [comment]
Whith the definition file "ALTHERMA(LT_CA_CB_11-16KW).h" y get this results:
 
[defALTHERMA(LT_CA_CB_11-16KW).h.txt](https://github.com/raomin/ESPAltherma/files/8424257/defALTHERMA.LT_CA_CB_11-16KW.h.txt)
