### ISSUE TITLE
Arduino Raspberry

### ISSUE THREAD

**Issue by coralblack12** [raomin/ESPAltherma#96]
Hi,
I have bought an ESP32 card at cost of 11 euro, now I would to buy a Raspberry or something else which can complete the system in order to read and publish data from the Daikin Pump. Could you suggest which card to buy to complete the interface without have the same investment of the Daikin Lan interface (around 200 euro)?

**Comment by raomin** [comment]
You'll need a server running HomeAssistant to fully benefit from ESPAltherma.
You can install Home Assistant on pretty much anything, but a Raspberry PI4 should work fine.

I'm also preparing a cloud based version that would push your data to Adafruit.IO but it's still a TODO for now...
